In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pylab as pl

def prettyPicture(clf, X_test, y_test):
    x_min =0.0; x_max = 1.0
    y_min =0.0; y_max = 1.0
    h=0.01
    xx,yy = np.meshgrid(np.arange(x_min,x_max,h),np.arange(y_min,y_max,h))
    Z = clf.predict(np.c_[xx.ravel(),yy.ravel()])

    Z = Z.reshape(xx.shape)

    plt.xlim(x_min,x_max)
    plt.ylim(y_min,y_max)

    plt.pcolormesh(xx,yy,Z,cmap= pl.cm.seismic)
    plt.show()

    # Plot also the test points
    grade_sig = [X_test[ii][0] for ii in range(0, len(X_test)) if y_test[ii]==0]
    bumpy_sig = [X_test[ii][1] for ii in range(0, len(X_test)) if y_test[ii]==0]
    grade_bkg = [X_test[ii][0] for ii in range(0, len(X_test)) if y_test[ii]==1]
    bumpy_bkg = [X_test[ii][1] for ii in range(0, len(X_test)) if y_test[ii]==1]

    plt.scatter(grade_sig, bumpy_sig, color = "b", label="fast")
    plt.scatter(grade_bkg, bumpy_bkg, color = "r", label="slow")
    plt.legend()
    plt.xlabel("PCA_1")
    plt.ylabel("PCA_2")

    plt.savefig("test.png")

In [5]:
x_min = 0.0; x_max = 1.0
y_min = 0.0; y_max = 1.0
h = .01

In [8]:
xx, yy =np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

In [10]:
xx.shape

(100, 100)

In [11]:
np.arange(x_min, x_max, h)

array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,
        0.18,  0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,
        0.27,  0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,
        0.36,  0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,
        0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,
        0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,
        0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,
        0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,
        0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,
        0.9 ,  0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99])

In [65]:
np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

[array([[ 0.  ,  0.01,  0.02, ...,  0.97,  0.98,  0.99],
        [ 0.  ,  0.01,  0.02, ...,  0.97,  0.98,  0.99],
        [ 0.  ,  0.01,  0.02, ...,  0.97,  0.98,  0.99],
        ..., 
        [ 0.  ,  0.01,  0.02, ...,  0.97,  0.98,  0.99],
        [ 0.  ,  0.01,  0.02, ...,  0.97,  0.98,  0.99],
        [ 0.  ,  0.01,  0.02, ...,  0.97,  0.98,  0.99]]),
 array([[ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
        [ 0.01,  0.01,  0.01, ...,  0.01,  0.01,  0.01],
        [ 0.02,  0.02,  0.02, ...,  0.02,  0.02,  0.02],
        ..., 
        [ 0.97,  0.97,  0.97, ...,  0.97,  0.97,  0.97],
        [ 0.98,  0.98,  0.98, ...,  0.98,  0.98,  0.98],
        [ 0.99,  0.99,  0.99, ...,  0.99,  0.99,  0.99]])]

In [66]:
np.c_[xx.ravel(),yy.ravel()]

array([[ 0.  ,  0.  ],
       [ 0.01,  0.  ],
       [ 0.02,  0.  ],
       ..., 
       [ 0.97,  0.99],
       [ 0.98,  0.99],
       [ 0.99,  0.99]])

In [63]:
yy.ravel()

array([ 0.  ,  0.  ,  0.  , ...,  0.99,  0.99,  0.99])

In [64]:
xx.ravel()

array([ 0.  ,  0.01,  0.02, ...,  0.97,  0.98,  0.99])